name: passkey_mobile_app
description: "Passkey-based device-linking demo"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  local_auth: ^2.1.7
  http: ^1.2.0
  pointycastle: ^3.7.3
  qr_code_scanner_plus: ^2.0.14
  permission_handler: ^12.0.1
  flutter_blue_plus: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
